name: Folder Change Notification

on:
  push:
    paths:
      - examples/**
      - smartcontracts/**
      - docs/**
  pull_request:
    paths:
      - examples/**
      - smartcontracts/**
      - docs/**

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or Update Issue
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');
            const { owner, repo } = github.context.repo;

            const issueTitle = 'Changes detected in examples, smartcontracts, or docs folder';

            const issueBody = `@simonerom Changes were detected in the 'examples', 'smartcontracts', or 'docs' folder. Please review the changes.`;

            try {
              const issues = await github.rest.issues.listForRepo({
                owner,
                repo,
                state: 'open',
                labels: 'notification'
              });

              if (issues.data.length === 0) {
                // Create a new issue if no open issues with the label exist
                await github.rest.issues.create({
                  owner,
                  repo,
                  title: issueTitle,
                  body: issueBody,
                  labels: ['notification']
                });
              } else {
                // Comment on the first open issue with the label
                const issueNumber = issues.data[0].number;
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issueNumber,
                  body: issueBody
                });
              }
            } catch (error) {
              console.error('Error creating or updating issue:', error);
              throw error;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
